version: '3.4'

services:
  tenantapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=4a6f27df-efce-4a41-a0bb-01d1db0ce237
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ${USERPROFILE}\.aspnet\https:C:\https:ro