version: '3.4'

services:
  tenantapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=718281828
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapplication.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ./%USERPROFILE%/.aspnet/https:/https
      #- C:/Users/Xiaomi/Desktop/cred:/https