version: 2.0
jobs: 
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:   
          working_directory: ~/project/WebApplication/TenantApplication
          name: Restore packages
          command: 
            dotnet restore
      - run:
          working_directory: ~/project/WebApplication/TenantApplication
          name: Build App
          command: 
            dotnet build
      - run:
          working_directory: ~/project/WebApplication/TenantApplication 
          environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
          ports:
            - "5001:443"
            - "5000:80"
          name: Run App
          command:
            dotnet run